# These are supported funding model platforms
# Uncomment and add your usernames/links

# github: YOUR_GITHUB_USERNAME
# patreon: YOUR_PATREON_USERNAME
# ko_fi: YOUR_KOFI_USERNAME
# custom: ["https://paypal.me/YOUR_PAYPAL", "https://www.buymeacoffee.com/YOUR_USERNAME"]
